import torch
from transformers import MarianMTModel, MarianTokenizer
from translation.translator import Translator


class HelsinkiTranslator(Translator):
    """
    The HelsinkiTranslator class is responsible for translating text and hidden states
    between Hebrew (source) and English (target) using the Helsinki-NLP MarianMT models.

    This class supports both direct text-to-text translation and the more advanced use case
    of translating hidden states generated by transformers or other models.

    Attributes:
        source_to_target_model_name (str): The model name for translating from source to target language.
        target_to_source_model_name (str): The model name for translating from target to source language.
        source_to_target_tokenizer (MarianTokenizer): Tokenizer for source to target translation.
        source_to_target_model (MarianMTModel): Pretrained MarianMT model for source to target translation.
        target_to_source_tokenizer (MarianTokenizer): Tokenizer for target to source translation.
        target_to_source_model (MarianMTModel): Pretrained MarianMT model for target to source translation.
    """

    def __init__(self, 
                 src_to_target_translator_model_name = 'Helsinki-NLP/opus-mt-tc-big-he-en',
                 target_to_src_translator_model_name = 'Helsinki-NLP/opus-mt-en-he'):
        """
        Initializes the HelsinkiTranslator with pretrained MarianMT models and tokenizers
        for translating between Hebrew and English.

        Models and tokenizers are loaded for both directions of translation:
        from Hebrew to English and from English to Hebrew.
        """

        
        src_to_target_tokenizer = MarianTokenizer.from_pretrained(self.src_to_target_translator_model_name)
        src_to_target_model = MarianMTModel.from_pretrained(self.src_to_target_translator_model_name,
                                                                    output_hidden_states=True)

        target_to_src_tokenizer = MarianTokenizer.from_pretrained(self.target_to_src_translator_model_name)
        target_to_src_model = MarianMTModel.from_pretrained(self.target_to_src_translator_model_name,
                                                                    output_hidden_states=True)
        
        
        super(src_to_target_translator_model_name, 
              target_to_src_translator_model_name,
              src_to_target_tokenizer,
              src_to_target_model,
              target_to_src_tokenizer,
              target_to_src_model
              )
        

        